#pragma config(Sensor, S1,     touch1,         sensorTouch)
#pragma config(Sensor, S2,     touch2,         sensorTouch)
#pragma config(Sensor, S4,     uss,            sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// NXT(master) to Arduino Uno(slave) I2C communication - joystick via rf




void AutoMode()
{
	int ussFwd = SensorValue[uss];
	if(ussFwd > 20)
	{
		motor[motorA] = 70;
		motor[motorC] = 70;
	}
	else
	{
		motor[motorA] = 0;
		motor[motorC] = 0;

		// measure distance to left
		nMotorEncoder[motorB] = 0;
		while(nMotorEncoder[motorB] < 73)
		{
			motor[motorB] = 30;
		}
		motor[motorB] = 0;
		wait1Msec(10);
		int ussLeft = SensorValue[uss];

		// measure distance to right
		while(nMotorEncoder[motorB] > -73)
		{
			motor[motorB] = -30;
		}
		motor[motorB] = 0;
		wait1Msec(10);
		int ussRight = SensorValue[uss];

		while(nMotorEncoder[motorB] < -16)
		{
			motor[motorB] = 30;
		}
		motor[motorB] = 0;

		//move back so robot can turn
		motor[motorA] = -50;
		motor[motorC] = -50;
		wait1Msec(300);
		motor[motorA] = 0;
		motor[motorC] = 0;

		// decide which way to go
		if(ussLeft < ussRight)
		{
			nMotorEncoder[motorA]= 0;
			while(nMotorEncoder[motorA] < 200)
			{
				motor[motorA] = 80;
				motor[motorC] = -80;
			}
			motor[motorA] = 0;
			motor[motorC] = 0;
		}
		else if(ussLeft > ussRight)
		{
			nMotorEncoder[motorC]= 0;
			while(nMotorEncoder[motorC] < 200)
			{
				motor[motorA] = -80;
				motor[motorC] = 80;
			}
			motor[motorA] = 0;
			motor[motorC] = 0;
		}
		else // distance to left = distance to right =255 <- error
		{
			nMotorEncoder[motorA]= 0;
			while(nMotorEncoder[motorA] < 150)
			{
				motor[motorA] = 80;
				motor[motorC] = -80;
			}
			motor[motorA] = 0;
			motor[motorC] = 0;
		}
	}
}



task main()
{
	int data1;
	int data2;
	int mPower;
	int direction;
	int switchAtoM;
	bool firstTimeAuto = true;
	int noConnection;
	bMotorReflected[motorA] = true;
	bMotorReflected[motorC] = true;
	SensorType(S3) = sensorI2CCustom;
	wait10Msec(10);

	while(true){

		data1 = 0; //can send data to arduino
		data2 = 0; // not used
		char msg[]={3, 10, data1, data2}; // first is sizeOf(msg)-1, second is the i2c address
		sendI2CMsg(S3, msg, 4);
		wait1Msec(20);
		char reply[4];
		readI2CReply(S3, reply, 4);

		mPower = reply[0] - 100;
		direction = reply[1] -50;
		switchAtoM = reply[2];
		noConnection = reply[3];


		if(switchAtoM == 0 && noConnection == 1)  //manual mode drive according to received joystick commands
		{
			motor[motorA] = mPower + direction*2/3;
			motor[motorC] = mPower - direction*2/3;
			firstTimeAuto = true;
		}
		else if(switchAtoM == 0 && noConnection ==0) //manual mode and no connection = stop
		{
			motor[motorA] = 0;
			motor[motorC] = 0;
		}
		else if(switchAtoM == 1) //autonomus mode
		{
			if(firstTimeAuto == true)
			{
				PlaySound(soundBeepBeep);
			}
			if(SensorValue[S1] == 0 && SensorValue[S2] == 0)
			{
				AutoMode();
			}
			else
			{
				motor[motorA] = -50;
				motor[motorC] = -50;
				wait1Msec(150);
				motor[motorA] = 0;
				motor[motorC] = 0;
				nMotorEncoder[motorA]= 0;
				while(nMotorEncoder[motorA] < 150)
				{
					motor[motorA] = 80;
					motor[motorC] = -80;
				}
				motor[motorA] = 0;
				motor[motorC] = 0;
			}
			firstTimeAuto = false;
		}

		nxtDisplayCenteredTextLine(3, "%d, %d",mPower);
		nxtDisplayCenteredTextLine(4, "%d, %d",direction);
		nxtDisplayCenteredTextLine(5, "%d, %d",switchAtoM);
		nxtDisplayCenteredTextLine(6, "%d, %d",noConnection);
	}
	wait1Msec(10);
}
