#pragma config(Sensor, S4,     uss,            sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// NXT(master) to Arduino Uno(slave) I2C communication - joystick via rf

void AutoMode()
{
	int ussFwd = SensorValue[uss];
	if(ussFwd > 15)
	{
		motor[motorA] = 70;
		motor[motorC] = 70;
	}
	else
	{
		motor[motorA] = 0;
		motor[motorC] = 0;

		// measure distance to left
		nMotorEncoder[motorB] = 0;
		while(nMotorEncoder[motorB] < 73)
		{
			motor[motorB] = 30;
		}
		motor[motorB] = 0;
		wait1Msec(10);
		int ussLeft = SensorValue[uss];

		// measure distance to right
		while(nMotorEncoder[motorB] > -73)
		{
			motor[motorB] = -30;
		}
		motor[motorB] = 0;
		wait1Msec(10);
		int ussRight = SensorValue[uss];

		while(nMotorEncoder[motorB] < -16)
		{
			motor[motorB] = 30;
		}
		motor[motorB] = 0;

		//move back so robot can turn
		motor[motorA] = -50;
		motor[motorC] = -50;
		wait1Msec(300);
		motor[motorA] = 0;
		motor[motorC] = 0;

		// decide which way to go
		if(ussLeft < ussRight)
		{
			nMotorEncoder[motorA]= 0;
			while(nMotorEncoder[motorA] < 200)
			{
				motor[motorA] = 80;
				motor[motorC] = -80;
			}
			motor[motorA] = 0;
			motor[motorC] = 0;
		}
		else if(ussLeft > ussRight)
		{
			nMotorEncoder[motorC]= 0;
			while(nMotorEncoder[motorC] < 200)
			{
				motor[motorA] = -80;
				motor[motorC] = 80;
			}
			motor[motorA] = 0;
			motor[motorC] = 0;
		}
	}
}



task main()
{
	int data1;
	int data2;
	int mPower;
	int direction;
	int switchAtoM;
	bool firstTimeAuto = true;
	bMotorReflected[motorA] = true;
	bMotorReflected[motorC] = true;
	SensorType(S3) = sensorI2CCustom;
	wait10Msec(1);

	while(true){

		data1 = 0; //can send data to arduino
		data2 = 0; // not used
		char msg[]={3, 10, data1, data2};
		sendI2CMsg(S3, msg, 3);
		wait1Msec(20);
		char reply[3];
		readI2CReply(S3, reply, 3);

		mPower = reply[0] - 100;
		direction = reply[1] -50;
		switchAtoM = reply[2];

		if(switchAtoM == 0)  //manual mode drive according to received joystick commands
		{
			motor[motorA] = mPower + direction/2;
			motor[motorC] = mPower - direction/2;
			firstTimeAuto = true;

		}
		else if(switchAtoM == 1) //autonomus mode
		{
			if(firstTimeAuto == true)
			{
				PlaySound(soundBeepBeep);
			}
			AutoMode();
			firstTimeAuto = false;
		}

		nxtDisplayCenteredTextLine(4, "%d, %d",mPower);
		nxtDisplayCenteredTextLine(5, "%d, %d",direction);
		nxtDisplayCenteredTextLine(6, "%d, %d",switchAtoM);

		wait1Msec(100);
	}
}
